"""
This file contains the list of tags used for classifying research papers.
Tags can be updated here without modifying the main application code.
"""

TAG_LIST = [
    "Adversarial Robustness",
    "Agents",
    "Autoregression",
    "Benchmark",
    "CNN",
    "Computational Efficiency",
    "Computer Vision",
    "Contrastive Learning",
    "Dataset",
    "Deep Learning",
    "Diffusion",
    "Encoder",
    "Ethics & Safety",
    "Evaluation Methods",
    "Explainable AI",
    "Federated Learning",
    "Few-Shot Learning",
    "Fine-tuning",
    "Foundation Model",
    "Generative AI",
    "Geometric DL",
    "GNN",
    "Graph Reasoning",
    "Graphs",
    "Human-AI Interaction",
    "In-context Learning",
    "Information Retrieval",
    "Knowledge Graphs",
    "Large Language Model",
    "Literature Review",
    "Message Passing NN",
    "Meta-Learning",
    "ML Theory",
    "Modality: Audio",
    "Modality: Graph",
    "Modality: Image",
    "Modality: Relational Data",
    "Modality: Text",
    "Modality: Video",
    "Multi Modal Modeling",
    "Neural Network",
    "Neuro-Symbolic AI",
    "NLP",
    "NN Architecture",
    "Optimization",
    "Philosophy of AI",
    "Planning Algorithms",
    "Prompt Engineering",
    "Reasoning Language Models",
    "Recommendation Systems",
    "Reinforcement Learning",
    "Retrieval Augmented Generation",
    "Robotics",
    "Self-Supervised Learning",
    "Shallow Embeddings",
    "Survey",
    "Test-time Learning",
    "Text-Attributed Graphs",
    "Transformer",
    "Tutorial",
    "Unsupervised Learning",
] 